name: Expo actions
on:
  push:
    branches:
      - main
      - develop
jobs:
  ValidateActor:
    runs-on: ubuntu-latest
    outputs:
      ACTOR: ${{ steps.actor.outputs.ACTOR }}
    steps:
      - id: actor
        run: |
          if [[ ${{ github.actor }} != *"[bot]" ]];then
              echo "::set-output name=ACTOR::true" 
          else
              echo "::set-output name=ACTOR::false" 
          fi
  Publish_Updates:
    name: Install and publish
    # if: ${{needs.ValidateActor.outputs.ACTOR}} == true
    runs-on: ubuntu-latest
    env:
      EAS_CHANNEL: ${{ github.ref_name == 'main' && 'production' || 'preview' }}
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: expo/expo-github-action@8.2.1
        with:
          eas-version: latest
          eas-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - run: npm install --force
        name: Install dependencies
      - run: eas update --channel=${{ env.EAS_CHANNEL }} --message "${{ github.event.head_commit.message }}"
  GenerateNewBuild:
    name: Build new artifact
    runs-on: ubuntu-latest
    needs: Publish_Updates
    env:
      EAS_PROFILE: ${{ github.ref_name == 'main' && 'production' || 'preview' }}
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: expo/expo-github-action@8.2.1
        with:
          eas-version: latest
          eas-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - run: npm install --force
      - run: eas build -p android --profile ${{ env.EAS_PROFILE }}
